/** Declaration file generated by dts-gen */

export = YouTube;

declare class YouTube {
    constructor(youtbeKey: string);

    searchVideos(keywork: string, size?: number): any;
    getChannelByID(id: string, optionsopt?: Object): Promise<any>;
}

declare namespace YouTube {

}


